[package]
name = "frodo"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.3.1", features = ["macros"] }
envy = "0.4"
serde = { version = "1.0.160", features = ["derive"] }
surrealdb = "1.0.0-beta.9"
thiserror = "1"
