version: "3.9"
services:
  api:
    restart: always
    build:
      context: .
      args:
        DATABASE_URL: $DATABASE_URL
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: "postgres"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASS
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $PG_USER"]
      interval: 1s
      timeout: 1s
      retries: 3