version: "3.9"
services:
  admin:
    restart: always
    build:
      context: admin/.
    ports:
      - 8001:8001
    depends_on:
      - api
  api:
    restart: always
    build:
      context: api/.
      args:
        DATABASE_URL: $DATABASE_URL
        API_PORT: $API_PORT
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - db
  db:
    image: "postgres"
    restart: always
    ports:
      - $PG_PORT:$PG_PORT
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASS
      POSTGRES_PORT: $PG_PORT
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $PG_USER"]
      interval: 1s
      timeout: 1s
      retries: 3