version: "3.9"
services:
  api:
    image: "ghcr.io/glesage/frodo:dev"
    restart: always
    ports:
      - 8000:8000
    environment:
      API_HOST: $API_HOST
      API_PORT: $API_PORT
      DATABASE_URL: $DATABASE_URL
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "postgres"
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $PG_USER"]
      interval: 1s
      timeout: 1s
      retries: 3