#build
FROM node:18-alpine AS builder
WORKDIR /app
COPY . .
RUN yarn install
RUN yarn build

#final
FROM node:18-buster-slim AS final
WORKDIR /app
COPY --from=builder ./app/dist ./dist
COPY package.json .
COPY yarn.lock .
RUN yarn install --production

ARG FRODO_API_PORT
ARG FRODO_SURREALDB_HOST
ARG FRODO_SURREALDB_PORT
ARG FRODO_SURREALDB_USERNAME
ARG FRODO_SURREALDB_PASSWORD
ARG FRODO_SURREALDB_NAMESPACE
ARG FRODO_SURREALDB_DATABASE

ENV FRODO_API_PORT=$FRODO_API_PORT
ENV FRODO_SURREALDB_HOST=$FRODO_SURREALDB_HOST
ENV FRODO_SURREALDB_PORT=$FRODO_SURREALDB_PORT
ENV FRODO_SURREALDB_USERNAME=$FRODO_SURREALDB_USERNAME
ENV FRODO_SURREALDB_PASSWORD=$FRODO_SURREALDB_PASSWORD
ENV FRODO_SURREALDB_NAMESPACE=$FRODO_SURREALDB_NAMESPACE
ENV FRODO_SURREALDB_DATABASE=$FRODO_SURREALDB_DATABASE

EXPOSE $FRODO_API_PORT

CMD [ "yarn", "start" ]