version: "3.3"
services:
  api:
    image: "ghcr.io/glesage/frodo:dev"
    restart: always
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: $DATABASE_URL
    depends_on:
      - db
  db:
    image: "postgres"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASS
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $PG_USER"]
      interval: 1s
      timeout: 1s
      retries: 3