version: "3.9"
services:
  admin:
    restart: always
    build:
      context: admin/.
    ports:
      - 8001:8001
    depends_on:
      - api
  api:
    restart: always
    build:
      context: api/.
      args:
        DB_POSTGRES_URL: $DB_POSTGRES_URL
        API_PORT: $API_PORT
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - postgres
  postgres:
    image: "postgres"
    restart: always
    ports:
      - $DB_POSTGRES_PORT:5432
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
      interval: 1s
      timeout: 1s
      retries: 3
  mongo:
    image: "mongo"
    restart: always
    ports:
      - $DB_MONGO_PORT:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASS
    volumes:
      - mongo:/data/db
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 1s
      timeout: 1s
      retries: 3

volumes:
  mongo: