version: "3.9"
services:
  api:
    restart: always
    build:
      context: .
      args:
        FRODO_API_HOST: "0.0.0.0"
        FRODO_API_PORT: 8080
        FRODO_SURREALDB_URL: "http://surreal:8000/rpc"
        FRODO_SURREALDB_USERNAME: "root"
        FRODO_SURREALDB_PASSWORD: "root"
        FRODO_SURREALDB_NAMESPACE: "ns"
        FRODO_SURREALDB_DATABASE: "sam"
    ports:
      - "8080:8080"
    depends_on:
      surreal:
        condition: service_healthy
  surreal:
    image: "surrealdb/surrealdb:latest"
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      SURREAL_LOG: warn
      SURREAL_USER: root
      SURREAL_PASS: root
      SURREAL_PATH: file:///data/database.db
      SURREAL_NO_BANNER: "1"
    command: start
    healthcheck:
      test: [ "CMD", "/surreal", "isready" ]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 1s