name: "Prepare .env"
description: "Copy root .env.example to .env"

runs:
    using: "composite"
    steps:
        - name: Create .env from example
          shell: bash
          working-directory: ${{ github.workspace }}
          run: cp .env.example .env
