name: marketplace

services:
  app:
    build:
      context: ../../
      dockerfile: ./services/marketplace/Dockerfile
      target: runner
    environment:
      - MARKETPLACE_GRPC_HOST=${MARKETPLACE_GRPC_HOST:-0.0.0.0}
      - MARKETPLACE_GRPC_PORT=${MARKETPLACE_GRPC_PORT}
      - MARKETPLACE_DB_DATABASE=${MARKETPLACE_DB_DATABASE:-marketplace}
      - API_PORT=${MARKETPLACE_GRPC_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_DOMAIN=host.docker.internal
    env_file:
      - ../../.env
    ports:
      - ${MARKETPLACE_GRPC_PORT}:${MARKETPLACE_GRPC_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
