name: API Tests

on:
    pull_request:
        branches: [dev]
    push:
        branches: [dev]

jobs:
    api:
        defaults:
            run:
                working-directory: api

        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup environment
              uses: ./.github/actions/setup-bun
              id: setup
              with:
                  working-directory: api
                  path-filter: 'api/**'

            - name: Run Tests
              if: steps.setup.outputs.has-changes == 'true'
              run: bun run test
              env:
                  DB_URL: postgres://localhost:5432/test
