name: API Build

on:
    pull_request:
        branches: [dev]
    push:
        branches: [dev]

jobs:
    api:
        defaults:
            run:
                working-directory: api

        timeout-minutes: 2
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup environment
              uses: ./.github/actions/setup-bun
              id: setup
              with:
                  working-directory: api
                  path-filter: 'api/**'

            - name: Install root dependencies
              if: steps.setup.outputs.has-changes == 'true'
              run: bun install
              working-directory: .

            - name: Run build
              if: steps.setup.outputs.has-changes == 'true'
              run: bun run build
