name: Web Tests

on:
    pull_request:
        branches: [dev]
    push:
        branches: [dev]

jobs:
    web:
        defaults:
            run:
                working-directory: web

        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup environment
              uses: ./.github/actions/setup-bun
              id: setup
              with:
                  working-directory: web
                  path-filter: 'web/**'

            - name: Setup Playwright
              if: steps.setup.outputs.has-changes == 'true'
              run: bun run test:setup

            - name: Build application
              if: steps.setup.outputs.has-changes == 'true'
              run: bun run build

            - name: Run Tests
              if: steps.setup.outputs.has-changes == 'true'
              run: bun run test

            - name: Upload test results
              uses: actions/upload-artifact@v4
              if: always() && steps.setup.outputs.has-changes == 'true'
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 1
