name: Web Lint

on:
    pull_request:
        branches: [dev]
    push:
        branches: [dev]

jobs:
    web:
        defaults:
            run:
                working-directory: web

        timeout-minutes: 1
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@latest

            - name: Setup environment
              uses: ./.github/actions/setup-bun
              id: setup
              with:
                  working-directory: web
                  path-filter: 'web/**'

            - name: Run lint
              if: steps.setup.outputs.has-changes == 'true'
              run: bun run lint

            - name: Upload test results
              uses: actions/upload-artifact@latest
              if: always() && steps.setup.outputs.has-changes == 'true'
              with:
                  name: lint-report
                  path: lint-report/
                  retention-days: 1
