name: web

services:
    app:
        build:
            context: ./
            dockerfile: ./Dockerfile
            target: runner
            args:
                - WEB_PORT=${WEB_PORT}
                - API_URL=${API_URL}
        environment:
            - WEB_PORT=${WEB_PORT}
            - API_URL=${API_URL}
        env_file:
            - ../.env
        ports:
            - ${WEB_PORT}:${WEB_PORT}
